name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main
      - deploy-to-EBS
  pull_request:
    branches:
      - main
      - deploy-to-EBS

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: bikashshah15/testspringbootapplication2:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'testspringbootapplication2'
          environment_name: 'Testspringbootapplication2-env'
          version_label: ${{ github.sha }}
          region: us-east-1
          image_tag: bikashshah15/testspringbootapplication2:latest
